basic_settings:
  site_title: Jayanth Prathipati
  favicon_image: 

header_settings:
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Projects'
      url: '/'
    - title: 'Blog'
      url: 'http://medium.com/@jayprat95'
    - title: 'About'
      url: '/about'



footer_settings:
  logo_image: 
  logo_width: 200
  footer_tagline: 

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 10

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: 'http://medium.com/@jayprat95'
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/in/jprathipati'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#00A3DA'
  border_color: '#eeeeee'
  overlay_background_color: '#00A3DA'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#2A2F36'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Montserrat|Raleway" rel="stylesheet">'
  title_font: '"Montserrat", sans-serif'
  body_font: '"Raleway", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""